Revert "Do not include non-standardized xlocale.h, include locale.h instead"
This reverts commit 274b2aee3bf65f139292d08a46d86f90d5ac8acb, which breaks in
external/icu on macOS, <https://ci.libreoffice.org/job/lo_tb_master_mac/20605/>:

> digitlst.cpp:497:8: error: unknown type name 'locale_t'
> static locale_t gCLocale = (locale_t)0;
>        ^