GenericSalLayout::KashidaJustify: STL assertion
error: attempt to compare a dereferenceable iterator to a singular iterator.
(regression from 6bb68cae7c31918eff8386d5b52be0759386bb60)