ScTabViewObj: fix STL assertion:
ScTabViewObj methods that invoke listeners need to be prepared for the
listener removing itself in the notification call, which some chart code
does when inserting a chart, resulting in assertion:
 error: attempt to increment a singular iterator.

Change-Id: I939afcc72d2b2040cd94113a0e159605d85ce592