Werror: C4324 structure was padded due to __declspec(align())
Change-Id: I5a065f9e875640bda2cab67733a5e2684f63d000
Reviewed-on: https://gerrit.libreoffice.org/14391
Tested-by: Michael Stahl <mstahl@redhat.com>
Reviewed-by: Michael Stahl <mstahl@redhat.com>