Revert "vcl: two printing headers should be private Unix headers"
This reverts commit 6b2889b3c4b2da175c4f95bde4495a1a89deedc3.
It breaks several TBs
eg:
/Users/cloph/source/libo-core/sw/source/uibase/dbui/dbmgr.cxx:140:10: fatal error: 'config_cups.h' file not found
         ^