use noexceptions .pch only when actually needed
Let's assume that all cxx objects use exceptions by default, unless explicitly
added using add_noexception_cxxobject. This should avoid the need to generate
noexceptions .pch in most cases, as noexceptions cxx objects are currently rare.
It also avoids a bug in MSVC that makes .pch generation fail with error C1033
(e.g. comment from 'Fish Fish' in
https://connect.microsoft.com/VisualStudio/feedback/details/98831/fatal-error-c1033-cannot-open-program-database-debug-vc80-idb).

Change-Id: I31c575a34539d58c42754ecfe6639c5b5e5854f1