tdf#98416 fix curl's configure check for nss (missing -lnssutil3)
without -lnssutil3, the configure check for nss fails when using
internal nss:
configure:24028: checking for SSL_VersionRangeSet in -lnss3
[…]
…/UnpackedTarball/nss/dist/out/lib/libnss3.so: undefined reference to
`NSSUTIL_ArgParseModuleSpecEx@NSSUTIL_3.21'

causing curl to build without ssl support:
SSL support:  no (--with-{ssl,gnutls,nss,polarssl,cyassl,axtls,winssl,darwinssl} )

This makes gdrive and other remote file methods fail

Change-Id: I098feb10a760c2f80a474d9205d6f1e403477efd