Revert "silence gcc4.8 warning"
This reverts commit a77ff8446e7ed2255b11406b4ccce7ec742d7c67.

GCC does not like the pragma:
error: ‘-Werror’ is not an option that controls warnings [-Werror=pragmas]

Change-Id: I8b97f39056091df644bcfe570332738560cd5dc3