Revert "fdo#62846 incorrect glyph to Unicode mappings in PDFs"
Breaks the build for Windows: vcl/win/source/gdi/winlayout.cxx(1897) :
error C2065: 'nCharPos' : undeclared identifier

This reverts commit 0b70e4ea4fcf0adccdfdf4886e5cc45d46479692.