remove broken DBG_UNHANDLED_EXCEPTION macro crap
this breaks quickly doing a `make sw debug=T` hard, with e.g.

 sw/source/ui/vba/vbasystem.cxx:239: undefined reference to `DbgUnhandledException(com::sun::star::uno::Any const&, char const*, char const*)'

fix this for --disable-dbgutl builds too before reverting this commit.

Change-Id: Ie54d63ea11b4e36c737b22099027711ad0435acc