revert USHORT->size_t change, breaks build
clone/components/cui/source/tabpages/borderconn.cxx:215:1: error: narrowing conversion of '-1u' from 'size_t' to 'short unsigned int' inside { }