Globally disable -Wcast-function-type new with upcoming GCC 8
...which unhelpfully even warns on reinterpret_cast, so causes failures like

> [CXX] sal/osl/unx/signal.cxx
> sal/osl/unx/signal.cxx: In function ‘bool onInitSignal()’:
> sal/osl/unx/signal.cxx:267:50: error: cast between incompatible function types from ‘void (*)(int, siginfo_t*, void*)’ to ‘{anonymous}::Handler1’ {aka ‘void (*)(int)’} [-Werror=cast-function-type]
>                                  oact.sa_sigaction);
>                                                   ^

And since all incompatible (but deliberate) casts between function types across
our code base should already be written as reinterpret_cast, we shouldn't lose
much by just disabling this new warning globally.

Change-Id: If15e9606e8fdc676b61012e31d7369653951ceca
Reviewed-on: https://gerrit.libreoffice.org/48431
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Stephan Bergmann <sbergman@redhat.com>