Fix Python problem in pyAltFCFGMerge at least on OS X
AttributeError: 'NoneType' object has no attribute 'write' when trying
to print to stdout and sys.stdout has been set to None.

Change-Id: Icb571b9e910d4ec393dc1fd246f867c02d5ac8e5