Revert "There's no reason for these defaults in one constructor but not the other"
The reason is that dbaccess_unoapi dbaccess.ORowSet fails with:

lib.StatusException: couldn't set up test environment
    at mod._dbaccess.ORowSet.createTestEnvironment(ORowSet.java:479)

This reverts commit 36caac0e029a3caf50cb27af339efd69008d414e.