Some builds seem to require a prefixed "system" here
... MacOSX-Intel@1-built_no-moz_on_10.6.8 complained with "oleembed.cxx:881:
error: "system" has not been declared"; and see previous
88d7f9fbe416d0f4c5edc4a9b5c9560d1d82167b "fwk139: #i10000# adopt for linux."

Change-Id: Ibd6f6aae69a7fcca7a60a85ed2d82dd5e775deea