tubes: warning guard for boost/signals2.hpp [-Werror=shadow]
boost 1.44 boost/signals2.hpp with gcc 4.6.3 causes
solver/unxlngx6/inc/boost/signals2/detail/slot_template.hpp:122:7: error:
declaration of ‘slot’ shadows a member of 'this' [-Werror=shadow]

Change-Id: I276e008aaebaca9c115bedc58d29c93c6dc526b8