fix "Wrap opencl-only functions in appropriate ifdef."
062871853cc420f35ddfbc2534f34c94f1b4c982
(loplugin:unreffun fix) caused:
  'undefined reference to `sc::FormulaGroupInterpreter::msInstance'
when building with --disable-opencl.

(It appears I didn't check whether my build had fully completed before pushing.)

Change-Id: I948205867985c7722662d673e95d5639bc9d9bcc