Add context attribute to translatable entry in .ui file.
a translatable entry without context attribute in 'fpicker/uiconfig/ui/explorefiledialog' causes
failure of 'make translation':
Traceback (most recent call last):
  File "/home/kiyotaka/Sources/libreoffice-testing/solenv/bin/uiex", line 30, in <module>
    keyid = entry.msgctxt + '|' + entry.msgid
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Error: Failed to execute /home/kiyotaka/Sources/libreoffice-testing/solenv/bin/uiex -i /home/kiyotaka/Sources/libreoffice-testing/fpicker/uiconfig/ui/explorerfiledialog.ui -o /home/kiyotaka/Sources/libreoffice-testing/workdir//pot/fpicker/messages.pot

Change-Id: Icdd5e283a30108b45f4b62967e2ce287d338b582
Reviewed-on: https://gerrit.libreoffice.org/41828
Tested-by: Jenkins <ci@libreoffice.org>
Reviewed-by: Katarina Behrens <Katarina.Behrens@cib.de>